export const DEFAULT_CONTINENT_OPTIONS = [
  { label: "プクランド大陸", value: "プクランド大陸", folder: "pukland_continent" },
  { label: "ウェナ諸島", value: "ウェナ諸島", folder: "wena_islands" },
  { label: "エルトナ大陸", value: "エルトナ大陸", folder: "eltona_continent" },
  { label: "ドワチャッカ大陸", value: "ドワチャッカ大陸", folder: "dwachakka_continent" },
  { label: "オーグリード大陸", value: "オーグリード大陸", folder: "ogreed_continent" },
  { label: "偽りのレンダーシア", value: "偽りのレンダーシア", folder: "false_lendersia" },
  { label: "真のレンダーシア", value: "真のレンダーシア", folder: "true_lendersia" },
  { label: "500年前の世界", value: "500年前の世界", folder: "500_years_ago" },
  { label: "大エテーネ島", value: "大エテーネ島", folder: "etene_islands" },
  { label: "ナドラガンド", value: "ナドラガンド", folder: "nadragand" },
  { label: "魔界", value: "魔界", folder: "makai" },
  { label: "天星郷", value: "天星郷", folder: "tensei" },
  { label: "オルセコ王国", value: "オルセコ王国", folder: "kyururu" },
  { label: "古エテーネ王国", value: "古エテーネ王国", folder: "kyururu" },
  { label: "古グランゼドーラ", value: "古グランゼドーラ", folder: "kyururu" },
   { label: "ウルベア帝国", value: "ウルベア帝国", folder: "kyururu" },
  { label: "アルウェーン", value: "アルウェーン", folder: "kyururu" },
  { label: "神話の時代", value: "神話の時代", folder: "kyururu" },

  { label: "果ての大地", value: "果ての大地", folder: "hate" },
  { label: "その他", value: "その他", folder: "others" },
];

export const DEFAULT_MAP_TYPE_OPTIONS = [
  { label: "フィールド", value: "field" },
  { label: "街", value: "town" },
  { label: "洞穴", value: "cave" },
  { label: "ダンジョン", value: "dungeon" },
  { label: "その他", value: "other" },
];

export const DEFAULT_LAYER_NAME_OPTIONS = [
  { label: "地上", value: "地上", fileName: "1" },
   { label: "1階", value: "1階", fileName: "1" },
  { label: "2階", value: "2階", fileName: "2" },
  { label: "3階", value: "3階", fileName: "3" },
  { label: "4階", value: "4階", fileName: "4" },
  { label: "5階", value: "5階", fileName: "5" },
  { label: "6階", value: "6階", fileName: "6" },
  { label: "7階", value: "7階", fileName: "7" },
  { label: "8階", value: "8階", fileName: "8" },
  { label: "9階", value: "9階", fileName: "9" },
  { label: "地下1階", value: "地下1階", fileName: "-1" },
  { label: "地下2階", value: "地下2階", fileName: "-2" },
  { label: "地下3階", value: "地下3階", fileName: "-3" },
  { label: "地下4階", value: "地下4階", fileName: "-4" },
  { label: "地下5階", value: "地下5階", fileName: "-5" },
  { label: "地下6階", value: "地下6階", fileName: "-6" },
  { label: "地下7階", value: "地下7階", fileName: "-7" },
 
  { label: "第一層", value: "第1層", fileName: "1" },
  { label: "第二層", value: "第2層", fileName: "2" },
   {label: "第三層", value: "第3層", fileName: "3" },
  { label: "第四層", value: "第4層", fileName: "4" },
  { label: "第五層", value: "第5層", fileName: "5" },
  { label: "第六層", value: "第6層", fileName: "6" },
  { label: "第七層", value: "第7層", fileName: "7" },
  { label: "上層", value: "上層", fileName: "zyoso" },
  { label: "中層", value: "中層", fileName: "cyuso" },
  { label: "下層", value: "下層", fileName: "kasou" },

  { label: "洞窟", value: "洞窟", fileName: "dokutsu" },
  { label: "中央", value: "中央", fileName: "chuo" },
  { label: "内部", value: "内部", fileName: "naibu" },
  { label: "通路", value: "通路", fileName: "aisle" },
  { label: "最上階", value: "最上階", fileName: "top" },
  { label: "駅", value: "駅", fileName: "station" },
];